### PR TITLE
Update for changes in remark

### PR DESCRIPTION
**Pull request by wooorm**
👋

### CODE REVIEW

**Review by Qard — APPROVED** [review]
This too, LGTM. 😸

**Comment by wooorm** [comment]
Awesome, thanks could you release this (I’d say major), then I can do `remark-lint-code-eslint`!

**Comment by Qard** [comment]
Will do! 🤖 

(You also have that power, btw!)

**Comment by Qard** [comment]
Released as v2.0.0.

**Comment by wooorm** [comment]
AWESOME! 👍

**Pull request merged**
